#!/bin/bash


# Compute Column without heat transfer

mpiexec -n 2 multiPhasePP


# Replace entries
sed -i 's/sigma 1.2/sigma sigmaReplace/g' properties/macroProperties
sed -i 's/startTime 0;/startTime 1000;/g' properties/simulation
sed -i 's/endTime 1000;/endTime 2000;/g' properties/simulation

mpiexec -n 2 multiPhasePP
